
package form;

import constants.Constants;

import java.awt.event.ItemEvent;
import javax.swing.JPanel;

/**
 *
 * @author lajos
 */
public class Settings extends javax.swing.JFrame implements Constants {

  private int nyelv, szin, erosseg;
  private final static int magyar = 1, angol = 0, sotet = 0, vilagos = 1;

  /**
   * Creates new form Settings
   */
  public Settings() {
    initComponents();
  }

  public Settings(int nyelv, int szin, int erosseg) {
    this.nyelv = nyelv;
    this.szin = szin;
    this.erosseg = erosseg;
    initComponents();
    nyelvBeallit();
    if (nyelv == magyar) {
      rbMagyar.setSelected(true);
    } else {
      rbAngol.setSelected(true);
    }
    if (szin == vilagos) {
      rbVilagos.setSelected(true);
    } else {
      rbSotet.setSelected(true);
    }
    if (erosseg == GYENGE) {
      rbKezdo.setSelected(true);
    } else {
      rbHalado.setSelected(true);
    }
    setLocationRelativeTo(null);
//        setVisible(true);
  }

  public int getNyelv() {
    return nyelv;
  }

  public int getErosseg() {
    return erosseg;
  }

  public int getSzin() {
    return szin;
  }

  public JPanel getGui() {
    return gui;
  }

  private void nyelvBeallit() {
    labelNyelv.setText((nyelv == magyar) ? "Nyelv:" : "Language:");
    labelSzin.setText((nyelv == magyar) ? "Szín:" : "Color:");
    labelLevel.setText((nyelv == magyar) ? "Szint:" : "Level:");
    rbHalado.setText((nyelv == magyar) ? "Haladó" : "Advanced");
    rbKezdo.setText((nyelv == magyar) ? "Kezdő" : "Beginner");
    rbVilagos.setText((nyelv == magyar) ? "Világos" : "White");
    rbSotet.setText((nyelv == magyar) ? "Sötét" : "Black");
    title.setText((nyelv == magyar) ? "Beállítások" : "Settings");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroupNyelv = new javax.swing.ButtonGroup();
    buttonGroupSzin = new javax.swing.ButtonGroup();
    buttonGroupLevel = new javax.swing.ButtonGroup();
    gui = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    rbMagyar = new javax.swing.JRadioButton();
    rbAngol = new javax.swing.JRadioButton();
    labelNyelv = new javax.swing.JLabel();
    jPanel5 = new javax.swing.JPanel();
    rbVilagos = new javax.swing.JRadioButton();
    rbSotet = new javax.swing.JRadioButton();
    labelSzin = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    rbKezdo = new javax.swing.JRadioButton();
    rbHalado = new javax.swing.JRadioButton();
    labelLevel = new javax.swing.JLabel();
    title = new javax.swing.JLabel();

    buttonGroupNyelv.add(rbMagyar);
    buttonGroupNyelv.add(rbAngol);

    buttonGroupSzin.add(rbVilagos);
    buttonGroupSzin.add(rbSotet);

    buttonGroupLevel.add(rbKezdo);
    buttonGroupLevel.add(rbHalado);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 165, 165)));

    rbMagyar.setFont(new java.awt.Font("FreeSerif", 0, 16)); // NOI18N
    rbMagyar.setText("Magyar");
    rbMagyar.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        nyelvItemStateChanged(evt);
      }
    });

    rbAngol.setFont(new java.awt.Font("FreeSerif", 0, 16)); // NOI18N
    rbAngol.setText("English");
    rbAngol.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        nyelvItemStateChanged(evt);
      }
    });

    labelNyelv.setFont(new java.awt.Font("FreeSerif", 0, 18)); // NOI18N
    labelNyelv.setText("Nyelv:");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(rbAngol)
          .addComponent(rbMagyar)
          .addComponent(labelNyelv))
        .addContainerGap(23, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addComponent(labelNyelv)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rbMagyar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rbAngol)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 165, 165)));

    rbVilagos.setFont(new java.awt.Font("FreeSerif", 0, 16)); // NOI18N
    rbVilagos.setText("Világos");
    rbVilagos.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        szinItemStateChanged(evt);
      }
    });

    rbSotet.setFont(new java.awt.Font("FreeSerif", 0, 16)); // NOI18N
    rbSotet.setText("Sötét");
    rbSotet.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        szinItemStateChanged(evt);
      }
    });

    labelSzin.setFont(new java.awt.Font("FreeSerif", 0, 18)); // NOI18N
    labelSzin.setText("Szín:");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelSzin)
          .addComponent(rbSotet)
          .addComponent(rbVilagos))
        .addContainerGap(22, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addComponent(labelSzin)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rbVilagos)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rbSotet)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 165, 165)));

    rbKezdo.setFont(new java.awt.Font("FreeSerif", 0, 16)); // NOI18N
    rbKezdo.setText("Kezdő");
    rbKezdo.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        levelItemStateChanged(evt);
      }
    });

    rbHalado.setFont(new java.awt.Font("FreeSerif", 0, 16)); // NOI18N
    rbHalado.setText("Haladó");
    rbHalado.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        levelItemStateChanged(evt);
      }
    });

    labelLevel.setFont(new java.awt.Font("FreeSerif", 0, 18)); // NOI18N
    labelLevel.setText("Szint:");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelLevel)
          .addComponent(rbHalado)
          .addComponent(rbKezdo))
        .addContainerGap(27, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addComponent(labelLevel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rbKezdo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rbHalado)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    title.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
    title.setText("Beállítások");

    javax.swing.GroupLayout guiLayout = new javax.swing.GroupLayout(gui);
    gui.setLayout(guiLayout);
    guiLayout.setHorizontalGroup(
      guiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(guiLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(26, 26, 26)
        .addGroup(guiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(title)
          .addGroup(guiLayout.createSequentialGroup()
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(49, Short.MAX_VALUE))
    );
    guiLayout.setVerticalGroup(
      guiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(title)
        .addGap(15, 15, 15)
        .addGroup(guiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(22, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(gui, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(gui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void nyelvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nyelvItemStateChanged
      if (evt.getStateChange() == ItemEvent.DESELECTED) {
        return;
      }
      javax.swing.JRadioButton rbtn = (javax.swing.JRadioButton) evt.getSource();
      nyelv = (rbtn == rbMagyar) ? magyar : angol;
      nyelvBeallit();
    }//GEN-LAST:event_nyelvItemStateChanged

    private void szinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_szinItemStateChanged
      if (evt.getStateChange() == ItemEvent.DESELECTED) {
        return;
      }
      javax.swing.JRadioButton rbtn = (javax.swing.JRadioButton) evt.getSource();
      szin = (rbtn == rbVilagos) ? vilagos : sotet;
    }//GEN-LAST:event_szinItemStateChanged

    private void levelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_levelItemStateChanged
      if (evt.getStateChange() == ItemEvent.DESELECTED) {
        return;
      }
      javax.swing.JRadioButton rbtn = (javax.swing.JRadioButton) evt.getSource();
      erosseg = (rbtn == rbKezdo) ? GYENGE : EROS;
    }//GEN-LAST:event_levelItemStateChanged


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroupLevel;
  private javax.swing.ButtonGroup buttonGroupNyelv;
  private javax.swing.ButtonGroup buttonGroupSzin;
  private javax.swing.JPanel gui;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JLabel labelLevel;
  private javax.swing.JLabel labelNyelv;
  private javax.swing.JLabel labelSzin;
  private javax.swing.JRadioButton rbAngol;
  private javax.swing.JRadioButton rbHalado;
  private javax.swing.JRadioButton rbKezdo;
  private javax.swing.JRadioButton rbMagyar;
  private javax.swing.JRadioButton rbSotet;
  private javax.swing.JRadioButton rbVilagos;
  private javax.swing.JLabel title;
  // End of variables declaration//GEN-END:variables
}
